# profiles.yml
osm_universal:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: './data/processed/{{ env_var("OSM_REGION_NAME", "region") }}.duckdb'
      extensions:
        - spatial
        - httpfs
        - json
      settings:
        memory_limit: "{{ env_var('DUCKDB_MEMORY_LIMIT', '64GB') }}"
        threads: "{{ env_var('DUCKDB_THREADS', '4') | int }}"
        max_temp_directory_size: "150GB" 
    
    prod:
      type: duckdb
      path: './data/processed/{{ env_var("OSM_REGION_NAME", "region") }}_prod.duckdb'
      extensions:
        - spatial
        - httpfs
        - json
      settings:
        memory_limit: "{{ env_var('DUCKDB_MEMORY_LIMIT', '32GB') }}"
        threads: "{{ env_var('DUCKDB_THREADS', '8') | int }}"
        
    small:
      type: duckdb
      path: './data/processed/{{ env_var("OSM_REGION_NAME", "region") }}_small.duckdb'
      extensions:
        - spatial
        - httpfs
        - json
      settings:
        memory_limit: "{{ env_var('DUCKDB_MEMORY_LIMIT', '8GB') }}"
        threads: "{{ env_var('DUCKDB_THREADS', '2') | int }}"